name: driver_tracking_flutter
description: Simple tracking app for drivers
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.0.0
  firebase_auth: ^1.0.0
  firebase_database: ^7.0.0
  location: ^4.4.0

flutter:
  uses-material-design: true
